ishikawa-beta
  Recompile user-configuration
    Raw user-configuration
      File
        Editor
        Workspace
      Scope
        Top-level
        Language-specific
    Editor scope
      Document URI
      Language mode